### PR TITLE
add labels config

### LINKED ISSUE #6: Add badges for training-center / training events to all training repositories
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to respond to your contribution.
To ensure that the right people get notified, you can tag some of the last contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your issue.

\- HSF Training
</details>

### PR DESCRIPTION
**Pull request by amanmdesai**
Closes #6
Closes https://github.com/hsf-training/hsf-training-singularity-webpage/issues/5

### CODE REVIEW

**Comment by amanmdesai** [comment]
Please do fix the file format, I am using .txt for now.

**Comment by klieret** [comment]
Very nice, thank you! (and sorry for having you do this piece of manual work...)

I'll merge it and see if it works :)   (it's a bit of a stupid workflow right now because I have to copy-paste this bit into the source of koji/github-label-manager but this will hopefully soon be changed)

**Comment by klieret** [comment]
@all-contributors please add @amanmdesai for data

**Comment by amanmdesai** [comment]
> Very nice, thank you! (and sorry for having you do this piece of manual work...)

You are welcome. 
 
> I'll merge it and see if it works :) (it's a bit of a stupid workflow right now because I have to copy-paste this bit into the source of koji/github-label-manager but this will hopefully soon be changed)

Just wanted to know. 
Is .txt format is acceptable by label-manager? from the format it seemed like a json file?

**Comment by klieret** [comment]
It's not quite json, because in json the keys of the dictionary would have to be marked as strings as well. It currently is copy-pasted into a typescript file ;)   I already changed the file ending accordingly

**Comment by amanmdesai** [comment]
oh okay. thanks.

**Pull request merged**
